### ISSUE TITLE
你好,现在项目是处于开发中还是已经比较完善了?

### ISSUE THREAD

**Issue by PhoenixZeng** [Liuguozhu/landlord#1]
我之前在码云上找了一款斗地主服务端,但是他的出牌校验有bug.所以想使用你这个库. 请问是否已经比较完善了.

**Comment by Liuguozhu** [comment]
我这个项目已经在线上跑了快一年了。目前没有玩家反馈有什么大问题。这个是从项目中提取出来的工具类

**Comment by PhoenixZeng** [comment]
好的.谢谢

**Comment by Liuguozhu** [comment]
不客气

在 2018-07-19 11:02:52，"火凌之" <notifications@github.com> 写道：


好的.谢谢
